/**
 * SC Toolkit Type Definitions
 *
 * Complete type system for all 9 Support Coordinator Toolkit features.
 * Covers: Report Synthesizer, CoC Cover Letter, Budget Forecaster,
 * Roster Analyzer, Justification Drafter, Senior Planner (re-exported),
 * Plan Management Expert, Visual Case Notes, and Weekly Summary.
 *
 * ZERO tolerance for 'any' types — all unknown data uses `unknown` with type guards.
 *
 * @packageDocumentation
 */

// ============================================================================
// 1. REPORT SYNTHESIZER TYPES
// ============================================================================

/**
 * Request payload for the Report Synthesizer feature.
 * Accepts raw report text and/or coordinator notes for AI synthesis.
 */
export interface SynthesisRequest {
  /** Raw clinical report text to synthesize */
  reportText?: string;
  /** Support coordinator notes guiding the synthesis */
  coordinatorNotes?: string;
}

/**
 * Template data structure for structured report output.
 * Maps to all required fields in an NDIS-compliant report template.
 */
export interface ReportTemplateData {
  participant_name: string;
  ndis_number: string;
  date_of_birth: string;
  report_type: string;
  assessment_date: string;
  provider: string;
  professional_name: string;
  functional_capacity: string;
  strengths: string;
  challenges: string;
  impact_on_daily_life: string;
  risks: string;
  mitigation_strategies: string;
  recommended_supports: string;
  frequency: string;
  duration: string;
  goals: string;
  summary: string;
}

/**
 * Result from the Report Synthesizer AI call.
 * Returns either synthesized text or structured template data.
 */
export interface SynthesisResult {
  /** Free-form synthesized report text */
  synthesizedText?: string;
  /** Structured template data for populating report templates */
  templateData?: ReportTemplateData;
  /** AI model used for generation */
  model: string;
}

// ============================================================================
// 2. COC COVER LETTER TYPES
// ============================================================================

/**
 * Request payload for the CoC Cover Letter generator.
 */
export interface CoCCoverLetterRequest {
  /** Full report text to base the cover letter on */
  reportText: string;
  /** Support Coordination level (Level 2 or Level 3) */
  scLevel: 2 | 3;
}

/**
 * Participant details for the cover letter header.
 */
export interface CoverLetterParticipant {
  name: string;
  dateOfBirth: string;
  ndisNumber: string;
  address: string;
  email: string;
  phone: string;
}

/**
 * Plan period information.
 */
export interface CoverLetterPlan {
  startDate: string;
  endDate: string;
  reportingPeriod: string;
}

/**
 * Key change entry describing a significant change event.
 */
export interface CoverLetterKeyChange {
  title: string;
  description: string;
}

/**
 * Clinical assessment measure for evidence section.
 */
export interface ClinicalAssessmentMeasure {
  measure: string;
  score: string;
  interpretation: string;
}

/**
 * Clinical evidence section of the cover letter.
 */
export interface CoverLetterClinicalEvidence {
  introText: string;
  assessments: ClinicalAssessmentMeasure[];
  conclusionText: string;
}

/**
 * SC level comparison data.
 */
export interface SCLevelComparison {
  currentLevel: string;
  recommendedLevel: string;
  currentHoursAnnual: string;
  recommendedHoursAnnual: string;
  currentHoursMonthly: string;
  recommendedHoursMonthly: string;
}

/**
 * SC activity area with description.
 */
export interface SCActivity {
  area: string;
  description: string;
}

/**
 * SC request section detailing level change justification.
 */
export interface CoverLetterSCRequest {
  introText: string;
  comparison: SCLevelComparison;
  activitiesIntro: string;
  activities: SCActivity[];
}

/**
 * Anticipated question and pre-drafted response.
 */
export interface AnticipatedQuestion {
  question: string;
  response: string;
}

/**
 * Included document reference.
 */
export interface IncludedDocument {
  name: string;
  date: string;
  pages: string;
}

/**
 * Progressive (pending) document reference.
 */
export interface ProgressiveDocument {
  name: string;
  expectedDate: string;
}

/**
 * Document evidence section of the cover letter.
 */
export interface CoverLetterDocuments {
  included: IncludedDocument[];
  progressive: ProgressiveDocument[];
  progressiveNote: string;
}

/**
 * Closing section of the cover letter.
 */
export interface CoverLetterClosing {
  statementText: string;
  priorityReasons: string[];
}

/**
 * Complete cover letter data structure generated by AI.
 */
export interface CoverLetterData {
  participant: CoverLetterParticipant;
  plan: CoverLetterPlan;
  overview: {
    summaryText: string;
  };
  keyChanges: CoverLetterKeyChange[];
  clinicalEvidence: CoverLetterClinicalEvidence;
  scRequest: CoverLetterSCRequest;
  anticipatedQuestions: AnticipatedQuestion[];
  documents: CoverLetterDocuments;
  closing: CoverLetterClosing;
}

// ============================================================================
// 3. BUDGET FORECASTER TYPES
// ============================================================================

/**
 * Input data for budget forecast calculation.
 */
export interface BudgetInput {
  totalBudget: number;
  spentAmount: number;
  planStartDate: string;
  planEndDate: string;
  coreBudget: number;
  coreSpent: number;
  capacityBudget: number;
  capacitySpent: number;
  capitalBudget: number;
  capitalSpent: number;
}

/**
 * Forecast result for a single budget category.
 */
export interface BudgetCategoryForecast {
  budget: number;
  spent: number;
  remaining: number;
  percentUsed: number;
  safeRate: number;
  actualRate: number;
}

/**
 * Complete budget forecast output.
 */
export interface BudgetForecast {
  /** Safe daily run rate (budget / total days) */
  safeRunRate: number;
  /** Actual daily run rate (spent / days elapsed) */
  actualRunRate: number;
  /** Number of days elapsed since plan start */
  daysElapsed: number;
  /** Number of days remaining until plan end */
  daysRemaining: number;
  /** Total plan duration in days */
  totalDays: number;
  /** Projected date when budget depletes (null if within budget) */
  projectedDepletionDate: string | null;
  /** Whether spending exceeds safe rate */
  isOverBudget: boolean;
  /** Remaining budget amount */
  remainingBudget: number;
  /** Percentage of total budget used */
  percentUsed: number;
  /** Breakdown by NDIS budget category */
  breakdown: {
    core: BudgetCategoryForecast;
    capacity: BudgetCategoryForecast;
    capital: BudgetCategoryForecast;
  };
}

// ============================================================================
// 4. ROSTER ANALYZER TYPES
// ============================================================================

/**
 * Single roster entry representing a worker shift.
 */
export interface RosterEntry {
  workerName: string;
  date: string;
  startTime: string;
  endTime: string;
  hoursWorked: number;
  participantName?: string;
  role?: string;
}

/**
 * Coverage gap identified in the roster.
 */
export interface CoverageGap {
  date: string;
  description: string;
}

/**
 * Overtime risk alert for a specific worker.
 */
export interface OvertimeRisk {
  workerName: string;
  totalHours: number;
  threshold: number;
}

/**
 * Summary statistics for a single worker.
 */
export interface WorkerSummary {
  name: string;
  shifts: number;
  totalHours: number;
  participants: string[];
}

/**
 * Complete roster analysis result.
 */
export interface RosterAnalysis {
  totalWorkers: number;
  totalShifts: number;
  totalHours: number;
  averageHoursPerWorker: number;
  coverageGaps: CoverageGap[];
  overtimeRisks: OvertimeRisk[];
  workerSummary: WorkerSummary[];
}

// ============================================================================
// 5. JUSTIFICATION DRAFTER TYPES
// ============================================================================

/**
 * Request payload for the SC Justification Drafter.
 * Comprehensive input for generating NDIS support justifications.
 */
export interface JustificationRequest {
  participantName: string;
  ndisNumber: string;
  dateOfBirth: string;
  planStartDate: string;
  planEndDate: string;
  scName: string;
  scOrganisation: string;
  itemName: string;
  itemCategory: string;
  requestedAmount: number;
  isReplacement: boolean;
  brokenItemDescription?: string;
  isLowRisk: boolean;
  trialRequired: boolean;
  functionalImpairments: string[];
  currentBarriers: string;
  dailyLivingImpact: string;
  participantGoals: string;
  goalAlignment: string;
  supplierName: string;
  quoteAmount: number;
  therapistEndorsement: boolean;
  additionalContext?: string;
}

/**
 * Result from the Justification Drafter AI call.
 */
export interface JustificationResult {
  success: boolean;
  justification: string;
  participantName: string;
  supportType: string;
  generatedAt: string;
}

// ============================================================================
// 6. SENIOR PLANNER TYPES — Re-exported from @/types/senior-planner
// ============================================================================

// Senior Planner types are already defined in src/types/senior-planner.ts
// and re-exported from src/types/index.ts. No duplication needed.

// ============================================================================
// 7. PLAN MANAGEMENT EXPERT TYPES
// ============================================================================

/**
 * Request payload for the Plan Management Expert feature.
 */
export interface PlanManagementRequest {
  /** User's question about plan management */
  query?: string;
  /** Base64-encoded file data for document analysis */
  fileData?: string;
  /** MIME type of the uploaded file */
  fileMimeType?: string;
  /** Original file name */
  fileName?: string;
  /** Whether to use the pro model for higher-quality results */
  useProModel?: boolean;
}

/**
 * Price guide reference entry returned by the expert.
 */
export interface PriceGuideReference {
  lineItem: string;
  category: string;
  description: string;
  priceLimit: string;
  notes: string;
}

/**
 * Document compliance issue with severity rating.
 */
export interface DocumentComplianceIssue {
  issue: string;
  severity: 'critical' | 'high' | 'medium' | 'low';
  recommendation: string;
}

/**
 * Document analysis findings.
 */
export interface DocumentFindings {
  documentType: string;
  complianceStatus: 'compliant' | 'needs_attention' | 'non_compliant' | 'not_applicable';
  issues: DocumentComplianceIssue[];
  strengths: string[];
  missingElements: string[];
}

/**
 * Structured response from the Plan Management Expert.
 */
export interface PlanManagementResponse {
  mainAnswer: string;
  keyPoints: string[];
  priceGuideReferences: PriceGuideReference[];
  verificationChecklist: string[];
  practicalGuidance: string[];
  commonMistakes: string[];
  documentFindings: DocumentFindings | null;
  relatedTopics: string[];
}

/**
 * Complete result from the Plan Management Expert AI call.
 */
export interface PlanManagementResult {
  queryType: 'question' | 'document_analysis' | 'general_inquiry' | 'needs_clarification';
  summary: string;
  response: PlanManagementResponse;
  confidenceLevel: 'high' | 'medium' | 'low';
  disclaimer: string;
}

// ============================================================================
// 8. VISUAL CASE NOTES TYPES
// ============================================================================

/**
 * Request payload for the Visual Case Notes feature.
 */
export interface CaseNoteRequest {
  /** Text content or description to generate case note from */
  content: string;
  /** Input type: text narrative or image for visual analysis */
  type: 'text' | 'image';
  /** Optional custom instructions for the AI */
  customInstructions?: string;
  /** Base64-encoded image data (required when type is 'image') */
  imageData?: string;
  /** MIME type of the image (required when type is 'image') */
  imageMimeType?: string;
}

/**
 * Result from the Visual Case Notes AI call.
 */
export interface CaseNoteResult {
  success: boolean;
  caseNote: string;
  model: string;
}

// ============================================================================
// 9. WEEKLY SUMMARY TYPES
// ============================================================================

/**
 * Request payload for the Weekly Summary feature.
 */
export interface WeeklySummaryRequest {
  /** Start date of the reporting period (ISO string) */
  startDate: string;
  /** End date of the reporting period (ISO string) */
  endDate: string;
}

/**
 * Activity statistics for the reporting period.
 */
export interface WeeklySummaryActivityStats {
  totalNotes: number;
  totalHours: number;
  participantsServed: number;
}

/**
 * Structured sections of the weekly summary.
 */
export interface WeeklySummarySections {
  achievements: string[];
  concerns: string[];
  goalProgress: string[];
  recommendations: string[];
  activityStats: WeeklySummaryActivityStats;
}

/**
 * Result from the Weekly Summary AI call.
 */
export interface WeeklySummaryResult {
  success: boolean;
  summary: string;
  sections: WeeklySummarySections;
}

// ============================================================================
// SC GOAL STRATEGIES TYPES
// ============================================================================

/**
 * Request payload for the SC Goal Strategies feature.
 */
export interface SCGoalStrategiesRequest {
  /** Participant's NDIS goals */
  goals: string[];
  /** Participant context information */
  participantContext?: string;
  /** Current support level */
  currentSupports?: string;
  /** Disability type(s) */
  disabilityTypes?: string[];
}

/**
 * Result from the SC Goal Strategies AI call.
 */
export interface SCGoalStrategiesResult {
  strategies: string;
  model: string;
}

// ============================================================================
// SC TOOLKIT FEATURE METADATA
// ============================================================================

/**
 * Feature status indicator.
 */
export type SCToolkitFeatureStatus = 'active' | 'beta' | 'coming_soon';

/**
 * Badge style for feature cards.
 */
export type SCToolkitBadge = 'new' | 'beta' | 'pro' | null;

/**
 * Tailwind color class prefix for feature theming.
 */
export type SCToolkitColor =
  | 'blue'
  | 'emerald'
  | 'amber'
  | 'purple'
  | 'rose'
  | 'indigo'
  | 'cyan'
  | 'teal'
  | 'orange';

/**
 * Metadata for a single SC Toolkit feature.
 */
export interface SCToolkitFeature {
  /** Unique feature identifier */
  id: string;
  /** Display name */
  name: string;
  /** Short description for feature cards */
  description: string;
  /** Lucide icon name */
  icon: string;
  /** Navigation href */
  href: string;
  /** Optional badge for feature cards */
  badge: SCToolkitBadge;
  /** Theme color */
  color: SCToolkitColor;
  /** Feature availability status */
  status: SCToolkitFeatureStatus;
}

/**
 * Complete metadata for all 9 SC Toolkit features.
 * Used for rendering the toolkit dashboard and navigation.
 */
export const SC_TOOLKIT_FEATURES: readonly SCToolkitFeature[] = [
  {
    id: 'report-synthesizer',
    name: 'Report Synthesizer',
    description: 'AI-powered synthesis of clinical reports into NDIS-compliant documentation with structured template output.',
    icon: 'FileText',
    href: '/dashboard/sc-toolkit/report-synthesizer',
    badge: 'new',
    color: 'blue',
    status: 'active',
  },
  {
    id: 'coc-cover-letter',
    name: 'CoC Cover Letter',
    description: 'Generate comprehensive Change of Circumstances cover letters with clinical evidence and SC level justification.',
    icon: 'Mail',
    href: '/dashboard/sc-toolkit/coc-cover-letter',
    badge: 'new',
    color: 'emerald',
    status: 'active',
  },
  {
    id: 'budget-forecaster',
    name: 'Budget Forecaster',
    description: 'Analyze NDIS plan budgets with run-rate projections, depletion forecasts, and category-level breakdowns.',
    icon: 'TrendingUp',
    href: '/dashboard/sc-toolkit/budget-forecaster',
    badge: null,
    color: 'amber',
    status: 'active',
  },
  {
    id: 'roster-analyzer',
    name: 'Roster Analyzer',
    description: 'Analyze worker rosters for coverage gaps, overtime risks, and workforce utilization patterns.',
    icon: 'Calendar',
    href: '/dashboard/sc-toolkit/roster-analyzer',
    badge: null,
    color: 'purple',
    status: 'active',
  },
  {
    id: 'justification-drafter',
    name: 'Justification Drafter',
    description: 'Draft NDIS-compliant support justifications with functional impairment mapping and goal alignment.',
    icon: 'Scale',
    href: '/dashboard/sc-toolkit/justification-drafter',
    badge: 'pro',
    color: 'rose',
    status: 'active',
  },
  {
    id: 'senior-planner',
    name: 'Senior Planner',
    description: 'Section 34 audit tool for NDIS compliance scoring, language fixes, and planner-ready summaries.',
    icon: 'Shield',
    href: '/dashboard/senior-planner',
    badge: null,
    color: 'indigo',
    status: 'active',
  },
  {
    id: 'plan-management-expert',
    name: 'Plan Management Expert',
    description: 'AI-powered NDIS plan management guidance with price guide references and document compliance analysis.',
    icon: 'BookOpen',
    href: '/dashboard/sc-toolkit/plan-management-expert',
    badge: 'new',
    color: 'cyan',
    status: 'active',
  },
  {
    id: 'visual-case-notes',
    name: 'Visual Case Notes',
    description: 'Generate structured NDIS case notes from text descriptions or photos with AI-powered clinical formatting.',
    icon: 'Camera',
    href: '/dashboard/sc-toolkit/visual-case-notes',
    badge: 'beta',
    color: 'teal',
    status: 'active',
  },
  {
    id: 'weekly-summary',
    name: 'Weekly Summary',
    description: 'AI-generated weekly summaries with achievements, concerns, goal progress, and activity statistics.',
    icon: 'BarChart3',
    href: '/dashboard/sc-toolkit/weekly-summary',
    badge: null,
    color: 'orange',
    status: 'active',
  },
] as const;

// ============================================================================
// TYPE GUARDS
// ============================================================================

/**
 * Type guard: Check if a value is a valid SynthesisRequest
 */
export function isSynthesisRequest(value: unknown): value is SynthesisRequest {
  if (typeof value !== 'object' || value === null) return false;
  const obj = value as Record<string, unknown>;
  return (
    (obj.reportText === undefined || typeof obj.reportText === 'string') &&
    (obj.coordinatorNotes === undefined || typeof obj.coordinatorNotes === 'string')
  );
}

/**
 * Type guard: Check if a value is a valid CoCCoverLetterRequest
 */
export function isCoCCoverLetterRequest(value: unknown): value is CoCCoverLetterRequest {
  if (typeof value !== 'object' || value === null) return false;
  const obj = value as Record<string, unknown>;
  return (
    typeof obj.reportText === 'string' &&
    (obj.scLevel === 2 || obj.scLevel === 3)
  );
}

/**
 * Type guard: Check if a value is a valid BudgetInput
 */
export function isBudgetInput(value: unknown): value is BudgetInput {
  if (typeof value !== 'object' || value === null) return false;
  const obj = value as Record<string, unknown>;
  return (
    typeof obj.totalBudget === 'number' &&
    typeof obj.spentAmount === 'number' &&
    typeof obj.planStartDate === 'string' &&
    typeof obj.planEndDate === 'string' &&
    typeof obj.coreBudget === 'number' &&
    typeof obj.coreSpent === 'number' &&
    typeof obj.capacityBudget === 'number' &&
    typeof obj.capacitySpent === 'number' &&
    typeof obj.capitalBudget === 'number' &&
    typeof obj.capitalSpent === 'number'
  );
}

/**
 * Type guard: Check if a value is a valid JustificationRequest
 */
export function isJustificationRequest(value: unknown): value is JustificationRequest {
  if (typeof value !== 'object' || value === null) return false;
  const obj = value as Record<string, unknown>;
  return (
    typeof obj.participantName === 'string' &&
    typeof obj.ndisNumber === 'string' &&
    typeof obj.itemName === 'string' &&
    typeof obj.itemCategory === 'string' &&
    typeof obj.requestedAmount === 'number' &&
    typeof obj.currentBarriers === 'string' &&
    typeof obj.participantGoals === 'string'
  );
}

/**
 * Type guard: Check if a value is a valid PlanManagementRequest
 */
export function isPlanManagementRequest(value: unknown): value is PlanManagementRequest {
  if (typeof value !== 'object' || value === null) return false;
  const obj = value as Record<string, unknown>;
  return (
    (obj.query === undefined || typeof obj.query === 'string') &&
    (obj.fileData === undefined || typeof obj.fileData === 'string') &&
    (obj.useProModel === undefined || typeof obj.useProModel === 'boolean')
  );
}

/**
 * Type guard: Check if a value is a valid CaseNoteRequest
 */
export function isCaseNoteRequest(value: unknown): value is CaseNoteRequest {
  if (typeof value !== 'object' || value === null) return false;
  const obj = value as Record<string, unknown>;
  return (
    typeof obj.content === 'string' &&
    (obj.type === 'text' || obj.type === 'image')
  );
}

/**
 * Type guard: Check if a value is a valid WeeklySummaryRequest
 */
export function isWeeklySummaryRequest(value: unknown): value is WeeklySummaryRequest {
  if (typeof value !== 'object' || value === null) return false;
  const obj = value as Record<string, unknown>;
  return (
    typeof obj.startDate === 'string' &&
    typeof obj.endDate === 'string'
  );
}

/**
 * Type guard: Check if a value is a valid SCGoalStrategiesRequest
 */
export function isSCGoalStrategiesRequest(value: unknown): value is SCGoalStrategiesRequest {
  if (typeof value !== 'object' || value === null) return false;
  const obj = value as Record<string, unknown>;
  return (
    Array.isArray(obj.goals) &&
    obj.goals.length > 0 &&
    obj.goals.every((g: unknown) => typeof g === 'string')
  );
}
